---
- name: Install ansible selinux support library
  package:
    name: "{{ (ansible_facts.python.version.major | int == 2) | ternary('libselinux-python','python3-libselinux') }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  become: true

- name: Install ansible selinux configure libraries
  package:
    name:
      - "{{ (ansible_facts.python.version.major | int == 2) | ternary('policycoreutils-python','python3-policycoreutils') }}"
      - "{{ (ansible_facts.python.version.major | int == 2) | ternary('libsemanage-python','python3-libsemanage') }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  become: true
  when: ansible_selinux.status == 'enabled'

- name: Enable connections to HTTP port
  seport:
    ports: '{{ slave_linux_selinux_ports }}'
    proto: tcp
    setype: http_port_t
    state: present
  become: true
  when:
    - ansible_selinux.status == 'enabled'
    - ansible_selinux.mode != 'disabled'
