---
- name: Copy service file
  win_template:
    src: service.cmd.j2
    dest: '{{ slave_windows_workdir }}/service.cmd'

- name: Install nssm
  win_chocolatey:
    name: nssm
    state: present

- name: Create a service via nssm
  win_nssm:
    name: '{{ slave_windows_service }}'
    application: '{{ slave_windows_workdir }}/service.cmd'
    state: present

- name: Start the service
  win_service:
    name: '{{ slave_windows_service }}'
    state: started
    username: '{{ slave_windows_service_user }}'
    password: '{{ slave_windows_service_password }}'
